server:
  port: 8081
spring:
  cloud:
    gateway:
      routes:
        - id: service_route
          uri: http://localhost:8080
          predicates:
            - Path=/car/**
          filters:
            - CustomFilter